# fly.toml app configuration file generated for whatsapp-backend-silent-mountain-8291 on 2025-12-10T22:02:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'whatsapp-backend-silent-mountain-8291'
primary_region = 'gru'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'whatsapp_data'
  destination = '/home/node/.wwebjs_auth'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
