// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://puyiyelqirhnzbcgiamf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1eWl5ZWxxaXJobnpiY2dpYW1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4ODk5NDUsImV4cCI6MjA4MDQ2NTk0NX0.2L7KUDpnslQlUCGh5Q4Iq_k-TmtMjm02-1vEyUZslzs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);